1. What is a Python library? Why do we use Python libraries?


A Python library is a collection of pre-written code that offers reusable functionalities to perform specific tasks or solve particular problems. 

We use Python libraries to save time, increase productivity, leverage community contributions, optimize performance.

2. What is the difference between Numpy array and List?

The main difference between a NumPy array and a list in Python is that a NumPy array is homogeneous and fixed-size, while a list is heterogeneous and variable-size. In other words, a NumPy array contains elements of the same data type and has a fixed shape, whereas a list can contain elements of different data types and its size can be changed dynamically.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3,4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
arr.size

12

In [4]:
arr.shape

(3, 4)

In [5]:
arr.ndim

2

4. Write python co^e to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
print(arr[0])

[1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

In [8]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
print(arr[2][3])

12


6. Write code to extract all odd-indexed elements from the given numpy array?

In [55]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original Array:",arr)

odd_arr=arr[1::2]
print("Odd Indexed Array:",odd_arr)

Original Array: [10 20 30 40 50 60 70]
Odd Indexed Array: [20 40 60]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [11]:
arr1=np.random.rand(3,3)

In [12]:
print(arr1)

[[0.68555016 0.30110426 0.20004379]
 [0.19094943 0.48425191 0.3218862 ]
 [0.87685461 0.57805027 0.88043476]]


8. Describe the difference between np.random.rand and np.random.randn?

In [13]:
arr2=np.random.rand(3,3)
#Gives only positive number

In [14]:
print(arr2)

[[0.38478667 0.75377298 0.51161112]
 [0.60406512 0.32982256 0.9201019 ]
 [0.15775978 0.96041031 0.05471864]]


In [15]:
 arr3=np.random.randn(3,3)
#Gives negative number also

In [16]:
print(arr3)

[[ 0.04409653  0.60774266 -0.1883591 ]
 [-0.36097851 -1.7641582   1.23831478]
 [-1.69455264  0.65133673 -0.53278967]]


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [17]:
arr4=np.expand_dims(arr,axis=0)
print(arr4)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [18]:
print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


In [19]:
a=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [20]:
b=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [21]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
#index wiLe multiplication
print(a*b)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [24]:
#matrix multiplication
#a @ b

we can not apply matrix multiplication .no of row not equal to no of column

In [25]:
#Add both the matrices
print(a+b)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [26]:
#Subtract matrix B from A
print(a-b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [27]:
#Divide Matrix B by A
print(b/a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12.  Which function in Numpy can be used to swap the byte order of an array?

In [28]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Byte order swap, also known as byte swapping or endian swapping, refers to the process of changing the byte order of data in memory.

In [30]:
arr=np.array([1,2,3,4,5,6])
swapped_arr=arr.byteswap()
print("Original Array:",arr)
print("Original Array:",swapped_arr)

Original Array: [1 2 3 4 5 6]
Original Array: [ 16777216  33554432  50331648  67108864  83886080 100663296]


13.  What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. 

In [39]:
sqr_mtx=np.array([[1,2],[3,4]])
inverse_mtx=np.linalg.inv(sqr_mtx)

print("Square Matrix:",sqr_mtx)
print("Square Matrix:",inverse_mtx)


Square Matrix: [[1 2]
 [3 4]]
Square Matrix: [[-2.   1. ]
 [ 1.5 -0.5]]


14. What does the np.reshape function do, and how is it used?


The np.reshape function in NumPy is used to change the shape of an array without changing its data. 

In [43]:
arr=np.random.randint(1,5,size=(3,4))
print(arr)

[[4 2 2 2]
 [3 1 4 4]
 [3 1 1 3]]


In [45]:
arr.reshape(12,1)

array([[4],
       [2],
       [2],
       [2],
       [3],
       [1],
       [4],
       [4],
       [3],
       [1],
       [1],
       [3]])

In [46]:
arr.reshape(2,6)

array([[4, 2, 2, 2, 3, 1],
       [4, 4, 3, 1, 1, 3]])

15. What is broadcasting in Numpy?

 Broadcasting refers to how Numpy handles array of different dimensions while performing any arithmetic operation.

In [52]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([10,11,12])
result=arr1+arr2
print("After Braodcasting:")
print(result)

After Braodcasting:
[[11 13 15]
 [14 16 18]
 [17 19 21]]
